### ISSUE TITLE
listTut Display

### ISSUE THREAD

**Issue by waihongteh** [AY2425S1-CS2103T-W08-1/tp#155]
![image](https://github.com/user-attachments/assets/28cccbd6-b211-49a7-97e3-048c5a2e6518)
I feel like adding Tutorial in between tutorial name and tutorial id does not work well though because T indicates tutorial already in the id.
Is it better to have it in such a format: 1. CS1010 (T1001) or something similar?

**Comment by Reallyeasy1** [comment]
It would be better to keep the Tutorial name inside, for better readability for the user
