### ISSUE TITLE
Inconsistent between user guide & application on attend & deletedAtd command 

### ISSUE THREAD

**Issue by SamsonChew** [AY2425S1-CS2103T-W08-1/tp#177]
1. There exits confusion between the use of attend & deletedAtd in application and markAtt & deleteAtt on user guide, please follow a consistent formatting issue as I am confused when I try to mark attendance.

<img width="780" alt="Screenshot 2024-10-27 at 5 07 40 PM" src="https://github.com/user-attachments/assets/eb1cd2c5-6d5e-45b7-a642-c1667a713809">
<img width="1002" alt="Screenshot 2024-10-27 at 5 08 52 PM" src="https://github.com/user-attachments/assets/6b33d898-9659-4f4e-8291-4872e6e3745a">

**Comment by tansanchian** [comment]
Solved!
