### ISSUE TITLE
[PE-D][Tester B] Incorrect  Getting Started command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#281]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/b12f1c6f-eaac-4c52-8fcf-f57861827b75.png)

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/f9934226-7e10-42f3-969a-6797ba06a170.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: JunLongling/ped#2

**Comment by tansanchian** [comment]
Will be solved in v1.6
