### ISSUE TITLE
[PE-D][Tester B] Incorrect add command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#286]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/5bb53fdb-92aa-4cd0-a50f-714fd1e7060c.png)

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/840c393e-7a6d-4956-9a4d-31930d55a9ce.png)

I enntered the same command from user guide but it says unknown command

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: JunLongling/ped#4

**Comment by SamsonChew** [comment]
will amend in v1.6
