### ISSUE TITLE
[PE-D][Tester E] Typo in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#294]
Page 4 of the UG has an extra type 'da' in the following:
addAtt s/A1234567X c/T1001 d/2024-01-24 : Adds student of id A1234567X attendance to the tutorial id T1001 on the da date 2024-01-24 .

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yyanyee/ped#6

**Comment by tansanchian** [comment]
Will be solved in v1.6
