### ISSUE TITLE
[PE-D][Tester E] Disallow use of S/O in names despite it being part of legal name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#299]
`addStu` command does not support names with special characters ie `/`. This is for the case of names that contain `S/O` or `D/O`

![Screenshot 2024-11-08 at 4.44.35 PM.png](https://raw.githubusercontent.com/yyanyee/ped/main/files/56d476ff-63f6-4f84-90fd-5de096e61ffe.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yyanyee/ped#7

**Comment by waihongteh** [comment]
This is indeed a valid issue! We have included this in our future enhancement. Thank you!
