### ISSUE TITLE
[PE-D][Tester A] Wrong naming of application in user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#301]
![image.png](https://raw.githubusercontent.com/Incogdino/ped/main/files/8178c06c-df75-4e8e-8bf4-e1820002c8c6.png)

I believe AddressBook should be renamed to TrackMate here instead.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Incogdino/ped#6

**Comment by Fui03** [comment]
Will update AddressBook data to TrackMate data.
