### ISSUE TITLE
[PE-D][Tester A] Wrong link in developer guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#304]
![image.png](https://raw.githubusercontent.com/Incogdino/ped/main/files/43f08e39-dc81-46ba-9ab6-3e9ba2349c42.png)

The link provided here is one of many that are linking to addressbook code instead of TrackMate.

This can be confusing for users who wishes to learn or contribute to TrackMate.

The links that I have identified to be faulty are: Main, UI, MainWindow, Logic, Model, Storage.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Incogdino/ped#8

**Comment by Fui03** [comment]
Will change the link to https://github.com/AY2425S1-CS2103T-W08-1/tp/blob/master/src/main/java/seedu/address/ui/Ui.java
