### ISSUE TITLE
[PE-D][Tester B] Edit Command cannot edit the name of the person even though the student ID is different

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#305]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/95fca067-ff32-463b-83ad-bd32fb0152a9.png)

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/615ac5e0-1b51-4915-b6e7-ad8d827739d3.png)

I cannot edit the name of the first person to Alice even though the student ID is different as specify by the user guide

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: JunLongling/ped#10

**Comment by SamsonChew** [comment]
will amend in v1.6
