### ISSUE TITLE
[PE-D][Tester B] When adding a person after the find command, it brings me back to the main list

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#312]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/8d91a0d9-c9aa-47bb-8420-7941b0ae3f16.png)
After find Samson, I want to add Alice, but it brings me to the main list and my find result disappear

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/b9095eb1-d66e-4d2e-b443-a9ec6c04a4b8.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: JunLongling/ped#11

**Comment by SamsonChew** [comment]
will explain this in user guide in v1.6 this aligns with our implementation idea
