### ISSUE TITLE
[PE-D][Tester D] Unable to add multiple tutorials to one student

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#317]
UG suggests that students can have multiple tutorials e.g. "list of tutorials"
![Screenshot 2024-11-08 at 5.07.18 PM.png](https://raw.githubusercontent.com/lim-jt/ped/main/files/76c7375e-de00-47d0-8cb7-42a16cc0ecb1.png)

However users are only able to change a student's tutorial class, not assign multiple tutorials to one student.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lim-jt/ped#6

**Comment by Fui03** [comment]
Will update user guide, one student will have exactly one tutorial only.
