### ISSUE TITLE
[PE-D][Tester B] The tutorial is not displayed in a separate view in the GUI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#319]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/4f441495-ac63-4657-8c82-d73e59b0c2d3.png)

Added Tutorial is not shown in a separate view in the GUI, Instead user have to use another command like listTut to see the added  tutorial

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/7f097849-491d-4490-8260-53b0cb1373a0.png)

This can caused inconvenience to the user if they want to see all the tutorial. The user have to keep enter the command listTut as upon entering other command, the list will be replace by the new command.

example after i type list, the listTut is gone

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/a50e48ae-3dae-4402-8838-fcc98383cb2f.png)

Also the user might forget what tutorial is already being added.
This can caused issue later when user wants to use the deleteTut command which needs the user to know the exact tutorial ID.
Also it waste the user time to type listTut again

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: JunLongling/ped#12

**Comment by waihongteh** [comment]
We plan to include this in future enhancement. Thank you!
