### ISSUE TITLE
[PE-D][Tester A] Lack a view to view student's completed assignment

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#324]
![image.png](https://raw.githubusercontent.com/Incogdino/ped/main/files/e393a897-f106-4da8-ae5f-274768f67462.png)

Would be nice if instead of a checkAsg method to individually check each assignment completion, it is displayed in the view as well.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Incogdino/ped#12

**Comment by waihongteh** [comment]
This design was adapted through careful consideration. If we would like to include a GUI for the assignments, this could make the window looks too cluttered, resulting in a negative user experience in terms of other aspects. To account for this, we have the listAsg and checkAsg commands which shows the statistics for each assignment. More importantly, as a tutor, I would probably check only one assignment at a time, and checkAsg solves the issue nicely without compromising other aspects. Hence, we do not consider this as a feature flaw, but rather a different design approach to the system, that is subjective.
