### ISSUE TITLE
[PE-D][Tester B] ASSIGNMENT_TITLE is not case insensitive when there is no need for it

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#348]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/eccfbff4-cfc9-4784-8412-12f6cdbec900.png)

For example, i have this  CS2103T Assignment 2
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/f0c0a5ea-d9cd-4af8-93a8-d6aced451587.png)

I cannot  do this markAsg 1 n/cs2103t assignment 2

![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/7003419a-bc5f-44f6-9ac8-442474c948d2.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: JunLongling/ped#23

**Comment by Fui03** [comment]
Will update user guide that assignment title is case-sensitive.

**Comment by waihongteh** [comment]
We also have included this into future enhancement! Thank you!
