### ISSUE TITLE
[PE-D][Tester B] Due date have no purpose

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-1/tp#352]
![image.png](https://raw.githubusercontent.com/JunLongling/ped/main/files/ad0b699c-6a90-461e-bcc6-9e19c6d7fe43.png)

The due date currently does not do anything even when the deadline is near or when the deadline has passed.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: JunLongling/ped#26

**Comment by waihongteh** [comment]
Consider things like email, phone number. They are there for documentation purposes and is going to be used when needed. Same goes for assignment due date. It is a must as due date is necessary for assignment in our context. Creating notification system or something like that around due date is beyond the scope of our current project, as if creating a system to send email based on the email inputted. Thanks for the suggestion though!
