### ISSUE TITLE
[PE-D][Tester A] Inconsistent mark command in user guide.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#360]
![image.png](https://raw.githubusercontent.com/Incogdino/ped/main/files/95ca0ecc-ce3c-4c1c-92f5-cc36f39b18fe.png)

Inconsistent example and command name. The attend command seems to be the wrong command. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Incogdino/ped#16

**Comment by SamsonChew** [comment]
will amend in v1.6 for consistency
