### ISSUE TITLE
[PE-D][Tester C] able to mark attendance twice for the same person for the same date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-1/tp#369]
![image.png](https://raw.githubusercontent.com/apollo-tan/ped/main/files/32de34ba-4689-42ee-874b-5ad95f6579bc.png)

This is related to the previous bug where you could delete the tutorial and the attendance of the person for that tutorial still persists. This allows the attendance of an infinite number of tutorials to be taken

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: apollo-tan/ped#16

**Comment by tansanchian** [comment]
This is another evidence that issue #363 is a functionality bug rather than a feature flaw.

Will be solved in v1.6
